version: "3.0"

services:
  nginx_php:
    build: #buildしたときのimage名はimageに指定した名前になる
      context: ./
      dockerfile: Dockerfile
    hostname: nginx_php
    image: nginx_php:latest
    container_name: nginx_php
    environment:
      TZ: Asia/Tokyo
    ports:
      - "80:80"
    # volumes:
    #   - ~/test/source/study_site:/var/www
    networks: 
      - common_link
    tty: true

networks:
  common_link:
    external: true
